pipeline:
  identifier: Build_debasiskar_devel_007_react_pipeline_sample_1700639009157
  name: Build react-pipeline-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1700638901936
        repoName: debasiskar-devel-007/react-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_build
                  spec:
                    shell: Sh
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: awsnew
                    region: eu-north-1
                    bucket: react-pipeline-test
                    sourcePath: /
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
